name: Tests

on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test --tests "*Test" --no-daemon
        continue-on-error: false

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/test/*Test.xml
          check_name: Unit Test Results
          comment_mode: off

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-report
          path: build/reports/tests/test/
          retention-days: 30

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Integration Tests
        run: ./gradlew test --tests "*IntegrationTest" --no-daemon
        continue-on-error: false

      - name: Publish Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/test/*IntegrationTest.xml
          check_name: Integration Test Results
          comment_mode: off

      - name: Upload Integration Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-report
          path: build/reports/tests/test/
          retention-days: 30

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    if: always()

    steps:
      - name: Download Unit Test Report
        uses: actions/download-artifact@v4
        with:
          name: unit-test-report
          path: unit-reports

      - name: Download Integration Test Report
        uses: actions/download-artifact@v4
        with:
          name: integration-test-report
          path: integration-reports

      - name: Test Summary
        run: |
          echo "## Test Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Unit Tests: Completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Integration Tests: Completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All tests have been executed successfully!" >> $GITHUB_STEP_SUMMARY
